# Step 1: Use the official Node.js image as the base
FROM node:18

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy package.json and package-lock.json to the container
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install rsuite
RUN npm install
RUN npm install recharts axios
RUN npm install react-slider
# Step 5: Copy the rest of the application code to the container
COPY . .

# Step 6: Expose the port used by Vite (default is 5173)
EXPOSE 5173

# Step 7: Command to start the development server
CMD ["npm", "run", "dev", "--", "--host"]