services:
  event-processor:
    build:
      context: ./event-processor
      dockerfile: Dockerfile
    container_name: event-processor
    restart: on-failure
    env_file:
      - path: ./event-processor/.env
        required: true
    