FROM redis:6.2

# Copy the minimal sentinel configuration into the image.
COPY sentinel.conf /etc/redis/sentinel.conf

# Copy the entrypoint script into the image.
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint.
CMD ["/entrypoint.sh"]